### ISSUE TITLE
Understanding 'SignificantTRades' UI

### ISSUE THREAD

**Issue by yohplala** [Tucsky/SignificantTrades#108]
Hi,
I cam accross SignificantTrades, and I have some questions regarding the list view.

1/
In the order list UI, I understand that orders are aggregated market orders per exchanges, and that aggregation is based on (basically it is l2_book):
- price
- exchange
- order side (sell or buy)
Do you confirm?
Does this mean that in the list view, if few seconds after, new orders appear at the same price than already existing ones, they are added to the already existing row?

2/
Well actually, I don't see the size of the orders changing. When they are being 'consumed' this is not shown right? Is there any way to show their filling rate?
At the moment, a user only knows an order has been filled, because the time counter is not shown any longer, right?

3/
On the left for some rows, there is an up or down arrow. What is its meaning? Does this mean that these positions are the best bid and best ask when they appeared?

Thanks for sharing this great piece of code and thanks for your feedback!
Bests,

**Comment by Tucsky** [comment]
1. Aggregated market orders yes, every order coming on the same instant (ms) are grouped into one (as long as it is the same exchange and side)

2. Once the aggr trade row pop in the UI, it means it is already filled / consumed. Not touching it after that (only grouping same ms trade, thats the key part)
The time on the left is based on the timestamp of the first trade of the group, no time = same time as trade below

3. The arrow is indeed the side of the trade (up means market buy, down means market sell), no arrow = same side as the trade below it.

More explanation on the aggregation [here](https://github.com/Tucsky/SignificantTrades/issues/103#issuecomment-644313716), its very simple stuff :)

**Comment by yohplala** [comment]
@Tucsky 
Hi Kevin,
Ok, fully clear! Thanks!
