### ISSUE TITLE
Historical data doesn't load on 4k screen

### ISSUE THREAD

**Issue by mutatrum** [Tucsky/SignificantTrades#112]
On a 4096x2180 screen the historical data doesn't load.

https://api.aggr.trade/btcusd/historical/1603970620000/1603982152503/10000 returns a 400 error with {"error":"too many bars"} as response. Zooming in to 125% or opening the debug view reduces the screen width to make it work.

**Comment by Tucsky** [comment]
Ive increased the limit, should be effective on the next server restart which should occur in about 6 or 7 hour
On another note, this tool is about live data not really the historical : I would not consider it a reliable source of information (except the 10s). The one that is printed as you let the thing run is.

**Comment by mutatrum** [comment]
Appreciated. 

The problem with the not loading the historical data is that it starts on an empty screen, and it takes several minutes to form something of a proper picture as there is no context on the y axis. Screenshot after 1 minute of live data:

![aggr](https://user-images.githubusercontent.com/56344102/97640417-f674a200-1a40-11eb-9a67-5102b14f29ca.png)

**Comment by mutatrum** [comment]
Fix confirmed, closing. Thank you, and thanks for the awesome project!
