### ISSUE TITLE
[Q] Why is there a server part?

### ISSUE THREAD

**Issue by wouterds** [Tucsky/SignificantTrades#14]
Hi

From a brief look I noticed the data is being proxied. Why is there even a server part, why not have the client interact directly with the websockets, reduces lag & load?

Cheers
Wouter

**Comment by Piterden** [comment]
Don't know why is the server part here exactly, but I have some issues with client HTTP connection to explorers on another project. Cause of CORS...

**Comment by Tucsky** [comment]
- You communicate directly with exchanges api to get trades (in the new version not demo), its much faster indeed 👍 
- Still need to proxy tradable assets from differents exchanges as this is REST api call and they do not allow CORS
