### ISSUE TITLE
Bug - Insignificant trades sound cannot be turned off

### ISSUE THREAD

**Issue by Sponge001** [Tucsky/SignificantTrades#18]
When the box is unchecked it still makes noise for trades above 10% of significant trades, Box reticks it's self.

**Comment by Tucsky** [comment]
Hmm I can very well believe how annoying that could be... sorry about that.
Everything works on my side tho, can you tell me the branch you are on, device information etc?

Thanks for reporting that

**Comment by Sponge001** [comment]
I am using chrome with the influx version. It could well be an issue with how I have installed it. There aren't really any instructions and what goes with what so I'm basically making a best guess as to how it all fits together.

Im assuming you take the legacy version and paste the influx client and server repositories over the top and install as normal?

**Comment by Tucsky** [comment]
That is right! readme completly outdated now :|

So basicaly to make it simple, you just need whats on "master" to make it work
`clone`, `npm install`, `npm run dev` and you done :)

/master is the new advanced version (that is running on https://aggr.trade)
/legacy is the old demo (that is running on http://tucsky.github.io/SignificantTrades)
/feature-server is the server part used by both master (for historical) and legacy (for historical AND websocket feed)

**Comment by Tucsky** [comment]
i will try to update readme soon 🤞

**Comment by Sponge001** [comment]
Hey thanks man, makes perfect sense! 

I just checked on https://aggr.trade and you can't turn insignificant trades noises off on that one either. If you deselect the button every time you press any other button it reselects.

**Comment by Sponge001** [comment]
Reset did not fix, Unsure what the note at the bottom of the console means. Could have something to do with it?
![image](https://user-images.githubusercontent.com/41725665/49345549-8b968100-f6da-11e8-981c-f587cceeb764.png)

**Comment by Tucsky** [comment]
Hmm no error in the log 🤔

**Comment by Tucsky** [comment]
I thought you were talking about the audio feature as a whole lol... my bad
Sounds like its fixed now :)
