### ISSUE TITLE
colours -> hard to read values

### ISSUE THREAD

**Issue by rranke** [Tucsky/SignificantTrades#24]
![Bildschirmfoto vom 2019-04-02 13:06:44](https://user-images.githubusercontent.com/5783257/55398293-7a566780-5548-11e9-9507-8d4e7647c6b6.png)

**Comment by rranke** [comment]
what does the colour "yellow" mean? 
is it a buy or a sell?

![1q](https://user-images.githubusercontent.com/5783257/55398349-978b3600-5548-11e9-99b0-8590fe94272f.png)

**Comment by Tucsky** [comment]
let me know what your threshold are
F12 + console tab 
> JSON.stringify(JSON.parse(localStorage.getItem('settings')).thresholds)

**Comment by rranke** [comment]
i just played around with these white dots and threshold values and already closed the window. 
so no stringify output possible anymore here :-(
