### ISSUE TITLE
TRXM19 price is always "0" (format problem?)

### ISSUE THREAD

**Issue by rranke** [Tucsky/SignificantTrades#25]
Instead of "$0" there should be something like "564 sats":

![Bildschirmfoto vom 2019-04-02 13:21:15](https://user-images.githubusercontent.com/5783257/55399025-4d0ab900-554a-11e9-83e5-8e554fd4df98.png)

![Bildschirmfoto vom 2019-04-02 13:21:28](https://user-images.githubusercontent.com/5783257/55399035-51cf6d00-554a-11e9-9a79-af125fef48b5.png)

**Comment by Tucsky** [comment]
Fixed in 97c65d3
