### ISSUE TITLE
Explosions

### ISSUE THREAD

**Issue by rranke** [Tucsky/SignificantTrades#26]
Normally, i would expect, that only trades ">1M" are "explosions" ?!?

![Bildschirmfoto vom 2019-04-02 13:29:45](https://user-images.githubusercontent.com/5783257/55399456-70823380-554b-11e9-9a06-13659c65e199.png)

**Comment by Tucsky** [comment]
By default any trade > 1M should show a "cash" related gif, but again cant know without seeing whats *your* thresholds looks like from the inside

If you can please enter this snippet in the console tab 🙏 
`JSON.stringify(JSON.parse(localStorage.getItem('settings')).thresholds)`

**Comment by rranke** [comment]
JSON.stringify(JSON.parse(localStorage.getItem('settings')).thresholds)

```
"[{\"amount\":\"30000\",\"gif\":null,\"buyColor\":\"rgba(76,175,80,.33)\",\"sellColor\":\"rgba(229,115,115,.33)\"},{\"amount\":\"100000\\n\",\"gif\":\"cash\",\"buyColor\":\"rgb(156,204,101)\",\"sellColor\":\"rgb(244,67,54)\"},{\"amount\":\"1000000\",\"gif\":\"explosion\",\"buyColor\":\"rgb(255,160,0)\",\"sellColor\":\"rgb(233,30,99)\"},{\"amount\":\"10000000\",\"gif\":null,\"buyColor\":\"rgb(91,130,48)\",\"sellColor\":\"rgb(224,91,82)\"}]"
```

**Comment by rranke** [comment]
with "explosions" i mean "animated"

**Comment by rranke** [comment]
Is this:
![Bildschirmfoto vom 2019-04-02 14:35:16](https://user-images.githubusercontent.com/5783257/55402811-a841a900-5554-11e9-835e-518c8b2ebac2.png)

the same like this:

![Bildschirmfoto vom 2019-04-02 14:36:01](https://user-images.githubusercontent.com/5783257/55402812-a841a900-5554-11e9-8045-538109641431.png)

??

**Comment by rranke** [comment]
it should look like the right one :-( and "300K" should not be "animated"

![Bildschirmfoto vom 2019-04-02 14:39:13](https://user-images.githubusercontent.com/5783257/55403004-1a19f280-5555-11e9-9140-174ad06f41c9.png)

**Comment by Tucsky** [comment]
> ```
> "[{\"amount\":\"30000\",\"gif\":null,\"buyColor\":\"rgba(76,175,80,.33)\",\"sellColor\":\"rgba(229,115,115,.33)\"},{\"amount\":\"100000\\n\",\**"gif\":\"cash\",**\"buyColor\":\"rgb(156,204,101)\",\"sellColor\":\"rgb(244,67,54)\"},{\"amount\":\"1000000\",\"gif\":\"explosion\",\"buyColor\":\"rgb(255,160,0)\",\"sellColor\":\"rgb(233,30,99)\"},{\"amount\":\"10000000\",\"gif\":null,\"buyColor\":\"rgb(91,130,48)\",\"sellColor\":\"rgb(224,91,82)\"}]"
> ```

your settings says "if trade >= 100000 and < 1000000 show **cash** gif"
and you don't have any gif for the 10M threshold
looks like you swapped thoses two

**Comment by rranke** [comment]
"you swapped thoses two" ->  ahhhhh okay. yes, that could be.
Maybe these four white dots should have a different size to make them visually distinguishable because the first white dot has a different business-logic than the last.

okay thanks, that helped.
