### ISSUE TITLE
[Request] Unfreeze the "Pair" option

### ISSUE THREAD

**Issue by devcarton** [Tucsky/SignificantTrades#3]
I'do like the possibility to change the pair and even if you already look it in BTC/USD. For exemple be able to have two windows with BTC/USD and ETH/USD (or ETH/BTC also) please.

**Comment by Tucsky** [comment]
Yep, this is coming very soon.

**Comment by Tucsky** [comment]
see https://github.com/Tucsky/SignificantTrades/tree/feature/standalone
