### ISSUE TITLE
Refactoring Req.: Standardise displayed currency values for better comparability

### ISSUE THREAD

**Issue by rranke** [Tucsky/SignificantTrades#31]
For example, TRX:

![Bildschirmfoto vom 2019-04-25 11:02:34](https://user-images.githubusercontent.com/5783257/56723628-a29d4480-6749-11e9-9fc8-dba8a5b9ab54.png)

- For **Binance** outputs:
"binance" --> Looks OK
"฿ 431 sats" --> Looks OK
"**฿ 0.6999354**" --> Looks Bad, better would be "**162K**" (for better comparability to bitmex outputs)

- For **Bitmex** outputs:
"bitmex" --> Looks OK
"**$** 438 sats" --> Looks Bad, better would be "**฿** 438 sats"
"**$** 58K" --> Looks Bad, because it is not "$" but TRX, so better would be to just display "**58K**"

better would be:

![yo](https://user-images.githubusercontent.com/5783257/56724226-dd53ac80-674a-11e9-84b7-5fde629a12b5.png)

**Comment by Tucsky** [comment]
Thanks! Just pushed a fix, now trxm19 should look like trxbtc from binance.
Damn thoses market are empty tho 

> "฿ 0.6999354" --> Looks Bad, better would be "162K" (for better comparability to bitmex outputs)
Agree, maybe I should add an option for that ?
When watching trxbtc or trxm19 trx is the _commodity_ and bitcoin the _currency_, the trade amount is shown in the currency way (_n_ bitcoins). For xbtusd usd is currency I show amount in $, simple.

73f8f96

**Comment by rranke** [comment]
> now trxm19 should look like trxbtc from binance.

Nooo!!!
I think you got me wrong!!!
I want to have that "trxbtc" looks like "trxm19" and NOT that "trxm19" should look like "trxbtc"

I want to have that "trxbtc" looks NOT like this:
![Bildschirmfoto vom 2019-04-25 16:01:58](https://user-images.githubusercontent.com/5783257/56741922-0d637580-6774-11e9-8167-674c54ba003c.png)

I want to have that "trxbtc" looks like this:
![Bildschirmfoto vom 2019-04-25 16:01:36](https://user-images.githubusercontent.com/5783257/56741901-050b3a80-6774-11e9-9411-1a321de3c0f9.png)





...this would be the correct visualisation of transaction history, as you can see on both, binance and bitmex...


bitmex:
![Bildschirmfoto vom 2019-04-25 16:08:18](https://user-images.githubusercontent.com/5783257/56742207-92e72580-6774-11e9-902c-d9ab40d5e70b.png)


binance:
![Bildschirmfoto vom 2019-04-25 16:08:08](https://user-images.githubusercontent.com/5783257/56742217-95497f80-6774-11e9-8dac-c37557791d80.png)


So, please show the value of traded TRX volume ("200K"), and NOT the related ฿-value (0,69999). 
THANKS

**Comment by Tucsky** [comment]
Haha I got you bro, that's why I let the issue open. 😄 
Still need to find a clean way to differentiate amount display whether the "currency" is btc/eth OR a fiat currency ($ € etc)

**Comment by rranke** [comment]
Okay, until then, please revert to previous version if possible :)

If it helps, you can always look at the exchanges transaction-history. Almost always, the SignificantTrades-app should display the same values, as in the exchanges transaction-history.

**Comment by Tucsky** [comment]
Nailed it 😁 
![image](https://user-images.githubusercontent.com/5738336/56815649-2dfa0100-6842-11e9-8515-205817d8872d.png)

**Comment by rranke** [comment]
yes, nice done, it seems to work!!!
pretty, even with logo :)


would it be much work to adjust the "THRESHOLDS" so that they match with displayed values?

currently it is like that the values match BTC values:
![Bildschirmfoto vom 2019-04-27 19:19:08](https://user-images.githubusercontent.com/5783257/56852917-5d336f80-6921-11e9-997e-6490a1ed4f40.png)


better and more convenient would be:
![Bildschirmfoto vom 2019-04-27 19:19:16](https://user-images.githubusercontent.com/5783257/56852920-602e6000-6921-11e9-8ec2-09ccc4e638c0.png)

**Comment by Tucsky** [comment]
🙏  Managing threshold in bitcoin was a real pain indeed!
