### ISSUE TITLE
[Feature Request] add option to just view the liquidations

### ISSUE THREAD

**Issue by mrhelloyellow** [Tucsky/SignificantTrades#32]
Hi!

Hope you are doing great! 
I really enjoy using your tool nice and clean!

I was wondering if possible to add option to just view the liquidations that would be a awesome feature imo.

Thanks for sharing!

**Comment by Tucsky** [comment]
Doing fantastic mate, thanks for the kind words ! 😄 
Imma add that soon

**Comment by Tucsky** [comment]
![image](https://user-images.githubusercontent.com/5738336/56916582-871f9a00-6ab9-11e9-823f-6c3e0d88c38b.png)
lil tick should do the job

**Comment by mrhelloyellow** [comment]
Just refreshed and saw the tick looking good!
Thank you very much for your time and effort!
