### ISSUE TITLE
Bug: XRP shows wrong amount for Liquidation

### ISSUE THREAD

**Issue by rranke** [Tucsky/SignificantTrades#33]
The amount for liquidations are incorrect.
Please check. 
THANKS

![Bildschirmfoto vom 2019-04-30 11:35:43](https://user-images.githubusercontent.com/5783257/56954055-25edda00-6b3e-11e9-8611-45ba560adc0d.png)

**Comment by Tucsky** [comment]
3317M liquidated short 🤑 
It seems that Bitmex send quantity in QUOTE currency for XBT & ETH perpetuals (qty in $) but BASE currency for every future markets (XRPM19 qty in XRP)
I always store in qty in base currency...

I am gonna wait for some more liqs for confirmation before I push a fix

**Comment by Tucsky** [comment]
Should be fixed by now
