### ISSUE TITLE
Change Req.: Please "remember" on client side, what the user entered in the field "Pair"

### ISSUE THREAD

**Issue by rranke** [Tucsky/SignificantTrades#34]
Please add functionality to "remember" on client side, what the user entered in the field "Pair" and do not replace that value for "Pair" with value out of URL.

For example, i use two URLs for "BTCUSD"

1.) https://btcusdbinance.aggr.trade/
2.) https://btcusdbitfinex.aggr.trade/

For both of them, i want to have the value "BTCUSD" in field "Pair"!!!!

BAD (app replaces my value with value out of URL):
![Bildschirmfoto vom 2019-04-30 11:57:50](https://user-images.githubusercontent.com/5783257/56954906-4e76d380-6b40-11e9-82bd-5dfe668de136.png)

GOOD (app remembers, that i have entered "BTCUSD":
![Bildschirmfoto vom 2019-04-30 11:58:10](https://user-images.githubusercontent.com/5783257/56954909-520a5a80-6b40-11e9-9613-25c9e542d3bc.png)

**Comment by Tucsky** [comment]
Done
