### ISSUE TITLE
Change Req.: Set all exchanges to multiplier "x1.00" by default

### ISSUE THREAD

**Issue by rranke** [Tucsky/SignificantTrades#36]
![Bildschirmfoto vom 2019-05-01 15:29:22](https://user-images.githubusercontent.com/5783257/57019850-de437d00-6c27-11e9-8848-37bfa6c2c126.png)

Today, i got tricked by this (#29) problem again...

I was very confused, why the cash-image was not showing up even though i had correctly set up my threshold-values. -> It was, because the exchange had its own multiplier (x0.66) :-(

I just thought, i musconfigured the threshold-values, or the app had a bug...but... it was only that the app had some threshold-multiplier for a specific exchange pre-configured (x0.66).

To avoid this "confusion" in the future and because of these reasons:

1.) It is pretty hard to set/use the threshold-regulator with the MOUSE for a specific exchange to exactly "x1.00" if it was set to x0.66 before :-(
2.) It is generally a pretty personal-specific setting and therefore should always start by "x1.00"
3.) For new app-users, it is definitely not obvious right from the start, that each exchange has its own "randomly-taken" x-multiplier. I think, this could heavily cause confusion :-(

i would recommend to set all exchanges to "x1.00" by default, and then, let the user decide, if he wants to adjust it for specific exchanges :-)

THANKS

**Comment by Tucsky** [comment]
The thing is most users don't touch any settings.

I will probably keep theses ratios when 
- not on a subdomain (except for btcusd)
- there is not stored properties (fresh load)

What do you think?

> It is pretty hard to set/use the threshold-regulator with the MOUSE for a specific exchange to exactly "x1.00" if it was set to x0.66 before :-(

Agree, I will add a "double clic to reset" on those

> For new app-users, it is definitely not obvious right from the start

Maybe I should write the multiplier next to the exchange name in the settings when != 1 (if I find the space for that) ?
Or in the welcome notice (the blue alert), a reminder of the exchanges with specific thresholds?

**Comment by rranke** [comment]
> I will probably keep theses ratios when...

No, i think this would make things even more complicated. 
I would prefer to set them all to x1.00 on a "fresh load / reset click". But this is my own opinion. So, maybe you or other users would like the have any fictional multipliers pre-configured. So, you decide if changes make sense here or not :-)

> Maybe I should write the multiplier next to the exchange name in the settings when != 1

Yes, seems good!

> Or in the welcome notice (the blue alert), a reminder of the exchanges with specific thresholds?

No, nobody reads or likes to read long texts :-)
Every setting/configuration should be obvious/visible and self-explaining without any clicks/reminders or long texts

**Comment by Tucsky** [comment]
![dblclicktoreset](https://user-images.githubusercontent.com/5738336/57864333-fc9aa280-77fb-11e9-826e-0c0380910b6f.gif)

**Comment by rranke** [comment]
Okay! 

Even though, i am not a big fan of sliders at all :D
Instead, I would prefer simple fields wherever possible, so that one can enter numbers by keyboard :)
...But now, it is at least possible to set it back to exactly x1.00, thats good!!

Small Bug:
Slider does not jump to the middle after doubleclick, tested on firefox.

![out](https://user-images.githubusercontent.com/5783257/57916633-877aac00-7893-11e9-923f-76ba73e0dd10.gif)
