### ISSUE TITLE
Sound settings

### ISSUE THREAD

**Issue by martin-tomasek** [Tucsky/SignificantTrades#37]
Please add more sound settings. I don't want the new sounds when SMA is crossed.

You're doing a great job. Thank you.

**Comment by Piterden** [comment]
Please, explain what exactly settings do you mean?

**Comment by martin-tomasek** [comment]
I would like to disable the new sounds that were added today. Looks like it's not on the SMA cross, but on a quick move. I don't know exactly what that sound means. Some checkbox where I could enable/disable the trades sounds and others.

**Comment by martin-tomasek** [comment]
Sorry. I have opened a new similar tool for price action. The new sounds came from here. :)
I noticed an update to your tool (the new exhanges), so I thought the sound had changed.
