### ISSUE TITLE
Sound and orders issues.

### ISSUE THREAD

**Issue by uzairpandith** [Tucsky/SignificantTrades#38]
Hello,
While using the app in Google Chrome:
- When I switch on the liquidations, the sound function stops working.

- For exchanges except bitmex, orders are not showing up.

**Comment by Tucsky** [comment]
> When I switch on the liquidations, the sound function stops working.

Are you talking about that switch ?
![image](https://user-images.githubusercontent.com/5738336/57507402-f047ae80-72fe-11e9-80f7-953b3b92c83e.png)

**Comment by uzairpandith** [comment]
Yes.

Also, orders aren't showing up for all exchanges except BitMEX

**Comment by Tucsky** [comment]
This switch is for showing liquidations ONLY, It filters everything else, the trades are ignored.
And the only exchange that provide liquidations infos is BitMEX.
The label "liqs" might be very missleading here tho, thats why I put a help tooltip that says "ONLY show liquidations" but yeah, need some more work I guess :)

**Comment by uzairpandith** [comment]
Should that block the sound alerts?

**Comment by Tucsky** [comment]
I guess, sounds are linked to the list, technically speaking and as per the actual look of it, if a trade show up, there is a sound, if trade is under threshold no sound. If liquidations only is enabled, trades are disabled no sounds as well. make sense to me but idk.

If thats really bothering you, this is the code that needs to be changed in src/component/TradeList.vue ligne 156 to 171

```
...
  return;
}

if (
  !silent && this.useAudio &&
  ((this.audioIncludeInsignificants && size > this.thresholds[1].amount * Math.max(0.1, multiplier) * 0.1) ||
    size > this.thresholds[1].amount * Math.max(0.1, multiplier))
) {
  this.sfx && this.sfx.tradeToSong(size / (this.thresholds[1].amount * Math.max(0.1, multiplier)), trade[4]);
}

if (this.liquidationsOnlyList) {
  return;
}

// group by [exchange name + buy=1/sell=0] (ex bitmex1)
const tid = trade[0] + trade[4];
const now = socket.getCurrentTimestamp();
...
```

**Comment by uzairpandith** [comment]
I am using your website https://btcusd.aggr.trade/ . So I request you to implement this in the same. 
Also regarding liqs issue, it's not showing for bitmex too now. Earlier it used to.
