### ISSUE TITLE
Chart stops updating after a while until an exchange is removed and re-added

### ISSUE THREAD

**Issue by canselcik** [Tucsky/SignificantTrades#39]
Console is filled with:
```
build.js?v=2.3.3:6 TypeError: Cannot read property 'update' of undefined
    at n.<anonymous> (build.js?v=2.3.3:30)
    at Array.forEach (<anonymous>)
    at n.updateData (build.js?v=2.3.3:30)
    at n.c (build.js?v=2.3.3:30)
    at build.js?v=2.3.3:30
    at Array.forEach (<anonymous>)
    at t.fireEvent (build.js?v=2.3.3:30)
    at build.js?v=2.3.3:30
    at Array.forEach (<anonymous>)
    at t.Chart.redraw (build.js?v=2.3.3:30)
```
which looks relevant. Happens on Chrome, Edge and as far as I remember also on Firefox.

**Comment by Tucsky** [comment]
Yes it is probably the most annoying bug of all, I spent hours trying to find the problem but can't figure it out...
For a quick workaround you can still disable the candlesticks but yeah to me its a highchart bug

**Comment by Tucsky** [comment]
it might be caused by the SMA indicator from highstock...
You may want to disable it 
![image](https://user-images.githubusercontent.com/5738336/57864686-a1b57b00-77fc-11e9-98ee-15f248898ca9.png)

**Comment by canselcik** [comment]
I will give that a try. Thanks. Definitely by far the most annoying bug of all. :)
