### ISSUE TITLE
aggr.trade down?

### ISSUE THREAD

**Issue by canselcik** [Tucsky/SignificantTrades#40]
Server seems to be down right now, just a heads up.

Frontend server seems down. CORS Proxy still seems to be functioning fine.

**Comment by Tucsky** [comment]
Working on a migration, shouldn't have taken that much time and effort but im having a hard time setting up the SSL on the new server :/
It should be back later tonight

**Comment by canselcik** [comment]
Sounds good, thanks for the update. :)

**Comment by Tucsky** [comment]
tucsky.github.io/SignificantTrades & aggr.trade are back online.
Thanks for letting me know btw! 👍
