### ISSUE TITLE
OKex Future volumes not showing correctly.

### ISSUE THREAD

**Issue by joyser** [Tucsky/SignificantTrades#42]
When trying to get OKex futures, the volumes are showing as Bitcoin/Ether amounts, and the volume values of the trades aren't matching with the live trade stream from OKex. Each contract on OKex is worth 100$ for BTC and 10$ for all the other contracts. Maybe we need to load this data, or have a setting to override the quote/base currency as I think its presuming those currencies wrong at the moment.

PS awesome tool, using it all the time.

**Comment by joyser** [comment]
Example would be EOS0628 as the pair which is OKex EOS futures expiring end of June 2019

**Comment by Tucsky** [comment]
Thanks, the number of contract wasn't calculated correctly, what I did here https://github.com/Tucsky/SignificantTrades/commit/72c44ff6683822290666682e1ce5e88962d88fe4 is obviously not working anymore.
I can't remember why I did that tho, something must have changed on the api??
Just passing reported volume is enough now

Then to have the exact same results as this trade feed from okex https://www.okex.com/futureTrade/futureMarket.do?currencyId=20&contractType=4 I had to disable trade grouping. Its the default behavior of this app, actually not an option, trades with the same timestamp (millisecond) & same side are merged into one.

For the base/quote currency symbol thing, yup, overriding them in the settings would be great 👍 
I changed the quote currency to bitcoin a few months ago, and "EOS0628" doesn't give any hint on the quote currency 😡

**Comment by joyser** [comment]
I think the two issues are intertwined with one another. From what I can see, If the app has detected that USD is the quote currency, then it presumes the volume from the trade is also in USD. See OKex BTC0628 on your app. This detects the quote currency as USD, and the volume it assumes is in USD, so When I hover the mouse over the volume of the trade it shows the Bitcoin value, presumably gotten by diving the volume of that trade by the price the trade was done at.
If however, you look at ETH0628, which has NOT detected USD as the quote currency, it presumes the volume is reported in the base currency, Which is ETH, and so when I however my mouse over the volume of an ETH0628 trade, I'm viewing the received volume, Multiplied by the price, (Where as it should still be divided like the BTC0628 contract.)
So presumably if we find a way to correctly define those other contracts as having the quotecurrency as USD, we could solve half the problem.

And this is what it looks like you were trying to do with 72c44ff , reversing the volume so the filter worked correctly. And then you multiplied the value by 100, this is because each trade of the OKex futures BTC contract is worth 100 dollars. so if it reports 10 volume trade, its actually $1,000. However, the other futures contracts are all $10... So, I'm not sure if you want to hard code these sort of things into the okex exchange file but that would be one workaround.

**Comment by joyser** [comment]
There's three issues it seems which are kind of intertwined here.
1) The app presumes reported volume is in the Base currency, whereas OKex futures are reported in the quote currency. Hence why you inverted it, I guess, in 72c44ff.
2) Okex futures are worth a multiplier of USD value. The bitcoin contract is worth 100$, which is what you have done in 72c44ff. However all the other futures are 10$
3) Because the app has not detected that EOS and ETH futures use USD as quote, it shows the base volume in the trade view, which is the correct contract value, but the incorrect number of ETH/EOS.

I can try and work on a solution a bit later in the week probably!

**Comment by Tucsky** [comment]
OK .. so I didn't knew, but Okex released v3 api in october last year! 
Ive looked into the doc and its actually pretty great, common/similar rest/ws endpoint for spot/margin/future/perps
We can't even acces perps or margin as of today using the current implementation !
This should fix everything.

I will try to push the update tomorrow 🙏

**Comment by Tucsky** [comment]
Api update

- SPOTS
**no changes** 
searching `BTCUSD` or `BTCUSDT` or `BTC-USDT` will track BTC-USDT

- FUTURES
-> searching `EOSUSD-THIS_WEEK` or `EOS-USD-190614` will track the eos weekly futures
-> `EOSUSD-NEXT_WEEK`
-> `EOSUSD-QUARTER`
*no more "EOSMMDD"!!*

- SWAP (perpetual derivative) **new**
-> searching `BTCUSD-SWAP` or `BTC-USD-SWAP` will do

Contract value is hard coded (100 for btc, 10 for everything else)

**Comment by joyser** [comment]
wow, great job! that's amazing dude!

**Comment by joyser** [comment]
could we change the counters so it reflects the quote currency volume instead of base currency volume?

**Comment by joyser** [comment]
Also, the '-' character in the URL: https://EOSUSD-quarter.aggr.trade seems to flag a security warning. All the other pairs work fine.

**Comment by Tucsky** [comment]
I think this particular issue is resolved now? Let me know if this switch 
![image](https://user-images.githubusercontent.com/5738336/59980309-47c28500-95f4-11e9-972c-8d3023cf9e3e.png) did the job

**Comment by joyser** [comment]
yeah perfect mate, all good
