### ISSUE TITLE
Are closed positions included as well?

### ISSUE THREAD

**Issue by shr808** [Tucsky/SignificantTrades#43]
Hi,
Thanks for your great project.
Is this code shows closed positions as well or does it only shows new opened positions. For example someone short 1mil at 9200 and closed it at 9180. Is it going to show both?

**Comment by Tucsky** [comment]
This app doesn't really show positions, it is made to track market orders filling limit orders. So yeah both will appear showing 1M sell at 9.2 and 1M buy at 9180.

**Comment by shr808** [comment]
Thanks. That's help a lot. So if i use limit orders and it filled gradually, it will not apear. Right?

**Comment by Tucsky** [comment]
nope! Only the market order(s) filling it :)
