### ISSUE TITLE
Documentation Req.: adding proxy config sample into readme (help to decreasing load on cors.aggr.trade)

### ISSUE THREAD

**Issue by n3m1** [Tucsky/SignificantTrades#51]

**Comment by Tucsky** [comment]
What are you looking for exactly?

just build with the CORS_URL env variable and start using your own cors server
CORS_URL=https://yourcorsserver.com/ npm run build
Then every rest calls will be made under "https://yourcorsserver.com/{the rest endpoint}"
ex: https://cors.aggr.trade/https://www.okex.com/api/spot/v3/instruments

The cors server is using https://github.com/Tucsky/thingproxy
