### ISSUE TITLE
ByBit logo not showing up....

### ISSUE THREAD

**Issue by francescoxio** [Tucsky/SignificantTrades#53]
Hi guys, do u know why when ByBit significant trades happen I don't get the logo, but if I chose letters I get the name?

THANKS in advance x ur help.

Screenshot below:
https://imgur.com/a/AoRfUBC

**Comment by Tucsky** [comment]
Unformately this exchange did not provided a proper svg logo. But thats the only one so if you see no logo, it can only be bybit :)

**Comment by Tucsky** [comment]
Its been added in the next version
https://github.com/Tucsky/SignificantTrades/blob/debt/2.5/static/exchanges/bybit.svg

**Comment by francescoxio** [comment]
Wow, thanks x such fast reply.
All cool then.


__________
FRANCESCO

**Comment by flyingscot5** [comment]
Currently using aggr.trade wondering when the change will be made live as the logo still does not show
