### ISSUE TITLE
Liqudations now showing

### ISSUE THREAD

**Issue by Miljan1771** [Tucsky/SignificantTrades#55]
I have very stupid question about liqudations. Where on the chart or on trades list are they supposed to show up ? Cause i have them enabled and i havent seen single one. I know they cant show if no liqudations happen, just curios if there is some seperate window where they are shown. Tnx

**Comment by joyser** [comment]
They appear in the trade list. And as far as I'm aware they will need to big as big as your threshold values as well. To test, you can open a new window, tick 'Show only liquidations', and then set all the thresholds to zero. You can compare the results with the liquidations on tensor charts. Note also that not all exchanges have liquidations published and/or integrated into the system. Bitmex defiantly does, so you can test with that.
