### ISSUE TITLE
NET::ERR_CERT_DATE_INVALID

### ISSUE THREAD

**Issue by davydof** [Tucsky/SignificantTrades#59]
![image](https://user-images.githubusercontent.com/10529679/67352754-87c15680-f559-11e9-8ba2-8e89ec0fbe16.png)

https://btcusd.aggr.trade/

@Tucsky

**Comment by davydof** [comment]
it's ok now, hmm

closed

**Comment by Tucsky** [comment]
Thank u for catching that! It is supposed to be fully automatic about ssl stuff renewal but somehow I had to restart the webserver this time... oops :(
