### ISSUE TITLE
OKEX (BTCUSD-QUARTER)-Significant trades data formatting issue 

### ISSUE THREAD

**Issue by nickersj** [Tucsky/SignificantTrades#61]
Dear Tucsky,

Could you please fix OKEX (BTCUSD-QUARTER)-Significant trades data formatting?

The VOL and order amounts are far greater than that have been or should be. i.e. reoccurring 10-100m+ orders that don't move the market, where bitmex and other exchanges are correct and (even in aggregate) are showing 100-500k orders, in comparison.

Thank you so much. Huge fan of your tool. Thanks again.

**Comment by nickersj** [comment]
![20191106_012031](https://user-images.githubusercontent.com/57443380/68299711-55366280-00f0-11ea-8d6f-7e9c50124a71.jpg)

**Comment by Tucsky** [comment]
I just pushed a fix, leme know how it is now :)

**Comment by nickersj** [comment]
Working perfectly again. 

Thanks Tucsky. Made my day!
