### ISSUE TITLE
Change Request: shorten the word "liquidated" to just "liq." for save space

### ISSUE THREAD

**Issue by rrarrarra** [Tucsky/SignificantTrades#68]
![Bildschirmfoto zu 2020-01-10 13-04-56](https://user-images.githubusercontent.com/5783257/72152378-12705f80-33ab-11ea-8bfd-960e6153b1fc.png)

currently, i cannot read the price, at which the liq. happened because 

or maybe instead of
`$ 35K liquidated SHORT @$128,95 SHORT` 

change it to 

`$35K @$128,95 SHORT liquidated`

**Comment by Tucsky** [comment]
yes its done
