### ISSUE TITLE
Enhancement Request:  Pop-up mode

### ISSUE THREAD

**Issue by husui007** [Tucsky/SignificantTrades#72]
I mainly use this app in pop-up mode.  As such, it would be nice if could consider following:  
- Remove address bar (takes up unecessary space)
- Name the browser window as currency pair

**Comment by Tucsky** [comment]
Good ideas!

**Comment by Tucsky** [comment]
Added exchange name...

**Comment by husui007** [comment]
Thanks 👍

I found a tool available on the Chrome Web Store that takes care of the other request I made.  It is called Open As Popup.  Really does wonders to clean my desktop up and saves alot of space for all the windows that I used to keep open in a browser or as an App.  

https://chrome.google.com/webstore/detail/open-as-popup/ncppfjladdkdaemaghochfikpmghbcpc

**Comment by Tucsky** [comment]
gotcha 👍 
I have no control on the address bar myself for security reasons (https://stackoverflow.com/questions/15926105/hiding-the-address-bar-of-a-browser-popup) 
but users can on their end if they really wants to (on chrome Open Main menu -> More Tools -> Create shortcut...)
