### ISSUE TITLE
Je n'ai pas d'affiché la chart

### ISSUE THREAD

**Issue by Aerithe77** [Tucsky/SignificantTrades#76]
Merci pour ton utilitaire, néanmoins je n'ai pas la chart qui s'affiche
![btc aggr](https://user-images.githubusercontent.com/43298687/77180010-9a6c9700-6ac9-11ea-8ba2-79d9837b2bbb.PNG)

**Comment by Tucsky** [comment]
le chart est en option... désactivé par défaut depuis peu. Si tu clique sur 
![image](https://user-images.githubusercontent.com/5738336/77189102-57b1bb80-6ad7-11ea-9ea4-a619fbf1a508.png) et scroll au niveau des settings du chart tu peu le réactiver... 

![image](https://user-images.githubusercontent.com/5738336/77189044-3d77dd80-6ad7-11ea-95a9-54a72999e6bf.png)

Si tu veux un conseil vas plutôt sur https://beta.aggr.trade/?showChart=true&pair=BTCUSD tu y trouvera un graphique de meilleur qualité :)
