### ISSUE TITLE
Option to remove graph

### ISSUE THREAD

**Issue by Sponge001** [Tucsky/SignificantTrades#8]
Hi Tucsky, When I download your app the first thing I do is change it so it doesn't display the graph. Do you think you could add the option to do this to make it easier for me and others?

Really appreciate the work youve done on this!

**Comment by Sponge001** [comment]
No issue with the graph, Just my screen space is precious and I don't use it. :)

**Comment by Tucsky** [comment]
Finally did that one 🙌 
26229e6417c56234c6efc5ca8bd4fbee3b2d0594
