### ISSUE TITLE
Cumulative Delta

### ISSUE THREAD

**Issue by mxkeeper** [Tucsky/SignificantTrades#83]
Please give back сumulative delta, or at least an option to show/hide it.

**Comment by Tucsky** [comment]
are you talking about the "deltas" in the stats panel?

**Comment by mxkeeper** [comment]
> are you talking about the "deltas" in the stats panel?

Yes, The table of 4 cells in the upper right corner.
This is very useful information for intraday trading and scalping. Really

**Comment by Tucsky** [comment]
Oh is it ? Welp I am thinking about removing that in next version. Wouldn't
that be easier to just plot it on chart and read it from here?
Also what settings u use for this panel?

**Comment by mxkeeper** [comment]
I found this option in the settings, it just was minimized. Many thanks! Topic can be closed
